import './globals.css'
// import Nav from '@/components/Nav'

export const metadata = {
  title: 'william.services',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#f5EBE0] dark:bg-[#22223b] transition-colors duration-500 dark:text-[#f5EBE0] text-[#22223b] overflow-x-hidden">
        {/* <Nav /> */}
        {children}
      </body>
    </html>
  )
}
